sprites.on_fire_created(function (location) {
    music.zapped.play()
    scene.createParticleEffectAtLocation(location, effects.fire)
    sprites.set_flame_strength(location, 5)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    myPlane,
    [img`
        ........................
        ........................
        ....ffffff..............
        ....f9bbbbf.........8f..
        .....ffbbbbff......88f..
        .....8ffff888ff...88bf..
        ..ffffbbbbbb8888888bbf..
        ffbb1bbbbbbbbbbbb888888f
        fbbbbddd99bbbbbbbbbfffff
        .f8bbbbbbbbb88bbbbf.....
        ..ff8888888bf88bbbbf....
        ....ffffffffff88bbbbb...
        ........cf.cf.f98888b...
        ...............ffffff...
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ....ffffff..........8f..
        ....f9bbbbff.......88f..
        .....8fffffff.....88bf..
        ..ffffbbbbbbff88888bbf..
        ffbbbd9999bbbbbbb888888f
        fbbbbbbbbbbbbbbbbbbfffff
        .f8bbbbbbbbb888bbbbf....
        ..ff8888888bf888bbbbb...
        ....fffffffffff98888b...
        ........cf.cf..ffffff...
        ........................
        ........................
        ........................
        `],
    100,
    true
    )
})
sprites.on_fire_destroyed(function (location) {
    music.thump.play()
    scene.clearParticleEffectsAtLocation(location)
    tiles.setTileAt(location, assets.tile`burnt tree`)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    myPlane,
    [img`
        ........................
        ........................
        ..............ffffff....
        ..f8.........fbbbb9f....
        ..f88......ffbbbbff.....
        ..fb88...ff888ffff8.....
        ..fbb8888888bbbbbbffff..
        f888888bbbbbbbbbbbb1bbff
        fffffbbbbbbbbb99dddbbbbf
        .....fbbbb88bbbbbbbbb8f.
        ....fbbbb88fb8888888ff..
        ...bbbbb88ffffffffff....
        ...b88889f.fc.fc........
        ...ffffff...............
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ..f8..........ffffff....
        ..f88.......ffbbbb9f....
        ..fb88.....fffffff8.....
        ..fbb88888ffbbbbbbffff..
        f888888bbbbbbb9999dbbbff
        fffffbbbbbbbbbbbbbbbbbbf
        ....fbbbb888bbbbbbbbb8f.
        ...bbbbb888fb8888888ff..
        ...b88889fffffffffff....
        ...ffffff..fc.fc........
        ........................
        ........................
        ........................
        `],
    100,
    true
    )
})
scene.onOverlapTile(SpriteKind.Water, assets.tile`tree fire`, function (sprite, location) {
    sprites.change_flame_strength_by(location, -1)
    sprite.destroy()
})
controller.A.onEvent(ControllerButtonEvent.Repeated, function () {
    sprites.spray(myPlane, forest_imgs.water)
})
let myPlane: Sprite = null
hud.fire_hud_label("Burning trees:")
hud.fire_hud(true)
game.set_strength_of_wind(3)
game.set_health_of_trees(7)
game.set_dryness_of_grass(3)
myPlane = sprites.create(img`
    . . . . . . . . . . . . . . f f f f f f . . . . 
    . . f 8 . . . . . . . . . f b b b b 9 f . . . . 
    . . f 8 8 . . . . . . f f b b b b f f . . . . . 
    . . f b 8 8 . . . f f 8 8 8 f f f f 8 . . . . . 
    . . f b b 8 8 8 8 8 8 8 b b b b b b f f f f . . 
    f 8 8 8 8 8 8 b b b b b b b b b b b b 1 b b f f 
    f f f f f b b b b b b b b b 9 9 d d d b b b b f 
    . . . . . f b b b b 8 8 b b b b b b b b b 8 f . 
    . . . . f b b b b 8 8 f b 8 8 8 8 8 8 8 f f . . 
    . . . b b b b b 8 8 f f f f f f f f f f . . . . 
    . . . b 8 8 8 8 9 f . f c . f c . . . . . . . . 
    . . . f f f f f f . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(myPlane)
scene.cameraFollowSprite(myPlane)
for (let index = 0; index < 4; index++) {
	
}
hud.danger_hud(true)
hud.fire_hud(true)
game.onUpdate(function () {
    sprites.random_spread()
})
